2025-03-03 00:40:50,372 INFO    MainThread:33026 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-03 00:40:50,373 INFO    MainThread:33026 [wandb_setup.py:_flush():67] Configure stats pid to 33026
2025-03-03 00:40:50,373 INFO    MainThread:33026 [wandb_setup.py:_flush():67] Loading settings from /Users/mark/.config/wandb/settings
2025-03-03 00:40:50,373 INFO    MainThread:33026 [wandb_setup.py:_flush():67] Loading settings from /Users/mark/Documents/college/NLP/Homeworks/HW4/wandb/settings
2025-03-03 00:40:50,373 INFO    MainThread:33026 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-03 00:40:50,374 INFO    MainThread:33026 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/mark/Documents/college/NLP/Homeworks/HW4/wandb/offline-run-20250303_004050-cdizi05c/logs/debug.log
2025-03-03 00:40:50,374 INFO    MainThread:33026 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/mark/Documents/college/NLP/Homeworks/HW4/wandb/offline-run-20250303_004050-cdizi05c/logs/debug-internal.log
2025-03-03 00:40:50,374 INFO    MainThread:33026 [wandb_init.py:init():761] calling init triggers
2025-03-03 00:40:50,374 INFO    MainThread:33026 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'max_vocab_size': 50000, 'hidden_size': 64, 'use_batch_norm': True, 'dropout': 0.5, 'weight_decay': 0, 'lr': 0.001, 'batch_size': 32, 'max_epochs': 5, 'early_stopping': 1, 'device': None, 'output_dir': None, 'wandb_project': 'nlp_module_3_assignment', '_wandb': {}}
2025-03-03 00:40:50,374 INFO    MainThread:33026 [wandb_init.py:init():784] starting backend
2025-03-03 00:40:50,374 INFO    MainThread:33026 [wandb_init.py:init():788] sending inform_init request
2025-03-03 00:40:50,396 INFO    MainThread:33026 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-03-03 00:40:50,396 INFO    MainThread:33026 [wandb_init.py:init():803] backend started and connected
2025-03-03 00:40:50,397 INFO    MainThread:33026 [wandb_init.py:init():896] updated telemetry
2025-03-03 00:40:50,398 INFO    MainThread:33026 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-03 00:40:50,517 INFO    MainThread:33026 [wandb_init.py:init():995] starting run threads in backend
2025-03-03 00:40:50,733 INFO    MainThread:33026 [wandb_run.py:_console_start():2377] atexit reg
2025-03-03 00:40:50,733 INFO    MainThread:33026 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-03 00:40:50,733 INFO    MainThread:33026 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-03 00:40:50,733 INFO    MainThread:33026 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-03 00:40:50,734 INFO    MainThread:33026 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-03 00:41:06,317 INFO    MainThread:33026 [wandb_watch.py:_watch():71] Watching
2025-03-03 00:41:07,063 WARNING MsgRouterThr:33026 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-03 00:41:07,064 INFO    MsgRouterThr:33026 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
